import './globals.css'
import type { Metadata } from 'next'
import {Montserrat} from 'next/font/google'
import { Header } from "@/app/Components";
import type {ReactNode} from "react";

const montserrat = Montserrat({
  subsets: ['cyrillic', 'latin'],
  weight: ['300', '400', '500', '600', '700'],
  fallback: ['Roboto', 'sans-serif']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <main>{children}</main>
        <footer>lolo</footer>
      </body>
    </html>
  )
}
